import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AdminSidebar from '@/components/sidebar/AdminSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EPASncII',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className='flex flex-row'>
        <aside>
          <AdminSidebar/>
        </aside>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
