import React from 'react';
import Provider from '@/components/Provider';
import AdminSidebar from '@/components/sidebar/AdminSidebar';
import AdminNavbar from '@/components/navbar/AdminNavbar';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'EPASncII',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en" className={inter.className}>
			<Provider>
				<body className='relative'>
					<aside className='z-80 hidden h-full bg-white md:fixed md:inset-y-0 md:flex md:w-20 md:flex-col lg:w-60'>
						<AdminSidebar/>
					</aside>
					<nav>
						<AdminNavbar/>
					</nav>
					<main className="h-screen bg-background pb-24 md:pl-20 lg:pl-60">
						{children}
					</main>
				</body>
			</Provider>
		</html>
	);
}