import UserSidebar from '@/components/sidebar/UserSidebar'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EPASncII',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
        <body className='relative h-screen'>
            <aside className='z-80 hidden h-screen bg-white md:fixed md:inset-y-0 md:flex md:w-20 md:flex-col lg:w-60'>
                <UserSidebar/>
            </aside>
            
            <main className="bg-background h-screen md:ml-20 lg:ml-60">
                {children}  
            </main>
        </body>
    </html>
  )
}